#! /bin/bash

echo $1 $2 $3 # $1 komut satırındaki birinci arguman ornek
#$0 kullanırsak da o scriptin adı ilk olarak yazılır
#ugur@ubuntu:~/Desktop/bashsamples$ ./dosyaadi arguman_bir arguman_iki arguman_uc
#gibi



