#! /bin/bash

# i=1

# while (( $i <= 10 ))
# do
#     echo $i
#     #i=$(($i+1)) #bir arttır i ye eşitle
#     ((i++)) #bir arttır i ye eşitle
#     sleep 0.1 # bir salise aralıklarla yazdır
#     #sleep 1 #bir saniye bekleterek yazdır
# done

#debug işlemi 3 şekilde yapılıyor

# 1- script dosyasında #! /bin/bash dedikten sonra -x 
# parametresini koymak

# 2- komut satırında bash -x scriptismi olarak çalıştırmak

# ya dosyasında
# 3- script içerisindeki kod kısmında debug edilecek
# kısma 

# set -x

# ---- kod kısmı--

# set +x 

# ifadesini koymak