#! /bin/bash

# ugur@ubuntu:~/Desktop/bashsamples$ sehir=istanbul
# ugur@ubuntu:~/Desktop/bashsamples$ echo ${sehir}
# istanbul
# ugur@ubuntu:~/Desktop/bashsamples$ echo ${sehir:-ankara}
# istanbul
# ugur@ubuntu:~/Desktop/bashsamples$ echo ${il:-ankara}
# ankara
# ugur@ubuntu:~/Desktop/bashsamples$ echo ${il}
#boş 


# ugur@ubuntu:~/Desktop/bashsamples$ echo ${nehir:?tanimsiz}
# bash: nehir: tanimsiz
# ugur@ubuntu:~/Desktop/bashsamples$ echo ${sehir:?tanimsiz}
# istanbul
# ugur@ubuntu:~/Desktop/bashsamples$ echo ${sehir:+malatya}
# malatya
# ugur@ubuntu:~/Desktop/bashsamples$ echo ${belediye:+malatya}

# ugur@ubuntu:~/Desktop/bashsamples$ echo ${#sehir}
# 8
# ugur@ubuntu:~/Desktop/bashsamples$ echo ${#il}
# 0
# ugur@ubuntu:~/Desktop/bashsamples$ echo ${sehir}
# istanbul
# ugur@ubuntu:~/Desktop/bashsamples$ echo ${sehir:3}
# anbul
# ugur@ubuntu:~/Desktop/bashsamples$ echo ${sehir:1:3}
# sta
